### ISSUE TITLE
Assign a value to each node

### ISSUE THREAD

**Issue by williamdes** [blabla-yy/rsbalancer#1]
While searching for a library to do some basic round robin between strings (IPs) I found your lib but no way to put a value.

This lib is less maintained, but has value support: https://crates.io/crates/weighted-rs

Could you add support for this ?

**Comment by blabla-yy** [comment]
Customize the node value? Try this
```
Node::new("ip", 1).unwrap();
// or
Node::new_with_default_weight("ip");
```
Or give me more details.

**Comment by williamdes** [comment]
Thank you
I will keep this in mind if I need this crate
For now I use another one: https://github.com/wdes/dns-ptr-resolver/blob/v1.1.0/src/main.rs#L92
